### PR TITLE
spring cleaning

### PR DESCRIPTION
**Pull request by m-edlund**
Upgraded a bunch of packages.

Fixed versions of some packages that cause the build to break on upgrading.

Lots of changes due to upgraded linter package, mostly renaming variables, moving around code and ensuring that context is still mounted after an await.

Added jobs for linting and executing the build runner.

### CODE REVIEW

**Comment by lrorpilla** [comment]
This PR is massive -- I understand what you want to do and it looks like this is mostly well intentioned.

We don't have unit tests, with resources being devoted to real-world use utility rather than QA utility, so I think we should run this version as a daily driver just for a few days and run by every change this has.

My biggest worry is the changes to navigation as this now uses `use_build_context_synchronously` as a linter rule so I want to make sure that there are no navigation bugs that result from this pull request.

I'll add some comments later but for the most part, this looks alright.

**Comment by lrorpilla** [comment]
[**Related issue**](https://github.com/creativecreatorormaybenot/wakelock/pull/203) on why there's issues upgrading `package_info_plus`. 

We can always use a dependency override but really I don't want this project to stack up on overrides.

I'll request some changes as I see which versions can still be upped and how to resolve any remaining dependency issues. I'll also run this on my main device for a few days to see if it's stable.

**Comment by lrorpilla** [comment]
- `file_picker: ^5.2.5` -> `file_picker: ^5.3.0`
- `package_info_plus: 3.0.3 #Error on upgrade maybe fix later` -> `package_info_plus: ^4.0.1`
- `wakelock: ^0.6.1+2` -> `wakelock: ^0.6.2`
- Below:
```
dependency_overrides:
...
    wakelock_windows:
    git:
      url: https://github.com/timsneath/wakelock
      ref: win32-v5
      path: wakelock_windows
```

Again, not necessarily changes requested yet. The issue linked above is still fresh so let's see how the community resolves this first as this merge is non-critical.

**Comment by lrorpilla** [comment]
@m-edlund 
There is a bug involving previewing the Term or Sentence Audio in this pull request. 

If you play a video and try to tap on a word and open the Card Creator, letting the audio play fully or partially, then closing the Creator and opening it again will retain the visual state of the sliders used for the audio preview widgets.

Additionally, these widgets will be frozen and you cannot play the audio. 

I've tried going back and forth on installing a version built from this pull request and the current live 2.7.1, opening the same video on the same line, repeating 10 times.

I can replicate the difference in behaviour for both versions, the version built from this PR will always have this misbehavior from the second time onwards, and the current live is fine and passes all trials.

Screenshot_20230520-204108

**Comment by m-edlund** [comment]
> * `file_picker: ^5.2.5` -> `file_picker: ^5.3.0`
> 
>     * `package_info_plus: 3.0.3 #Error on upgrade maybe fix later` -> `package_info_plus: ^4.0.1`
> 
>     * `wakelock: ^0.6.1+2` -> `wakelock: ^0.6.2`
> 
>     * Below:
> 
> 
> ```
> dependency_overrides:
> ...
>     wakelock_windows:
>     git:
>       url: https://github.com/timsneath/wakelock
>       ref: win32-v5
>       path: wakelock_windows
> ```

Managed to upgrade a couple more packages. 
Done. 

> There is a bug involving previewing the Term or Sentence Audio in this pull request.

This was due to the audioplayer being disposed in onCreatorClose, along with the listeners in the audio fields. To fix this I set the initialization flag to false in onCreatorClose so the Listeners get recreated and create a new audioplayer instance on audio initialization.
Then I also fixed a bug in the audio slider where the old state of the field was used, sometimes causing the current position of the slider to be higher than the max value (causing a big red debug box). Also cleaned up the slider code slightly while I was there.

**Comment by lrorpilla** [comment]
There's another artifact in the newest commit, when in dark mode (not sure if also in light), the colours of the audio slider changes when it doesn't in current 7.2.1.

Again, I appreciate it and no rush -- I want this merged in but just want to be cautious and not have to suddenly do any reverts.

**Comment by m-edlund** [comment]
Rebased and fixed slider being grey after it finishes playing audio.

**Pull request merged**
